In [0]:
import numpy as np

In [0]:
import torch

In [0]:
import helper
import matplotlib.pyplot as plt

In [0]:
from torchvision import datasets,transforms

In [0]:
def activation(x):
    """ Sigmoid activation function 
    
        Arguments
        ---------
        x: torch.Tensor
    """
    return 1/(1+torch.exp(-x))

In [0]:
transforms =transforms.Compose([transforms.ToTensor(),\
                                transforms.Normalize((0.5),(0.5))])

In [0]:
trainset= datasets.MNIST('~/.pytorch/MNIST_data/',download =True,train=True,transform=transforms)

Extracting /root/.pytorch/MNIST_data/MNIST/raw/train-images-idx3-ubyte.gz to /root/.pytorch/MNIST_data/MNIST/raw


Extracting /root/.pytorch/MNIST_data/MNIST/raw/train-labels-idx1-ubyte.gz to /root/.pytorch/MNIST_data/MNIST/raw


Extracting /root/.pytorch/MNIST_data/MNIST/raw/t10k-images-idx3-ubyte.gz to /root/.pytorch/MNIST_data/MNIST/raw


Extracting /root/.pytorch/MNIST_data/MNIST/raw/t10k-labels-idx1-ubyte.gz to /root/.pytorch/MNIST_data/MNIST/raw
Processing...
Done!


/pytorch/torch/csrc/utils/tensor_numpy.cpp:141: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program.


In [0]:
trainloader =torch.utils.data.DataLoader(trainset,batch_size=64,shuffle=True)

In [0]:
dataiter =iter(trainloader)
images,labels =dataiter.next()

In [0]:
print(type(images))
print(images.shape)
print(labels.shape)

<class 'torch.Tensor'>
torch.Size([64, 1, 28, 28])
torch.Size([64])


In [0]:
im=images.flatten

In [0]:
images.resize_(64,784)

tensor([[-1., -1., -1.,  ..., -1., -1., -1.],
        [-1., -1., -1.,  ..., -1., -1., -1.],
        [-1., -1., -1.,  ..., -1., -1., -1.],
        ...,
        [-1., -1., -1.,  ..., -1., -1., -1.],
        [-1., -1., -1.,  ..., -1., -1., -1.],
        [-1., -1., -1.,  ..., -1., -1., -1.]])

In [0]:
images

tensor([[-1., -1., -1.,  ..., -1., -1., -1.],
        [-1., -1., -1.,  ..., -1., -1., -1.],
        [-1., -1., -1.,  ..., -1., -1., -1.],
        ...,
        [-1., -1., -1.,  ..., -1., -1., -1.],
        [-1., -1., -1.,  ..., -1., -1., -1.],
        [-1., -1., -1.,  ..., -1., -1., -1.]])

In [0]:
weights = torch.randn_like(images)

In [0]:
n_input = images.shape[1]     # Number of input units, must match number of input features
n_hidden = 256                   # Number of hidden units 
n_output = 10                    # Number of output units

# Weights for inputs to hidden layer
W1 = torch.randn(n_input, n_hidden)
# Weights for hidden layer to output layer
W2 = torch.randn(n_hidden, n_output)

# and bias terms for hidden and output layers
B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))

In [0]:
p=torch.mm(activation(torch.mm(images,W1)+B1),W2) + B2

In [0]:
p.shape

torch.Size([64, 10])

In [0]:
def sigmoid(x):
  return torch.exp(x)/torch.sum(torch.exp(x),dim=1).view(-1,1)

In [0]:
r=sigmoid(p)

In [0]:
r.shape

torch.Size([64, 10])

In [0]:
r

tensor([[6.2531e-15, 2.6024e-08, 1.7613e-07, 2.3568e-10, 1.0000e+00, 9.2149e-16,
         8.1938e-09, 3.1170e-09, 2.1689e-08, 3.1683e-09],
        [3.7708e-11, 2.0885e-10, 1.7805e-01, 1.0392e-10, 7.4933e-04, 3.2759e-11,
         1.6265e-06, 8.2115e-01, 4.2386e-05, 1.7308e-06],
        [1.5179e-10, 7.9778e-10, 3.6649e-01, 1.3010e-08, 4.2306e-01, 8.1770e-14,
         5.7383e-06, 4.8217e-04, 2.0996e-01, 7.6348e-11],
        [3.2052e-06, 1.7841e-07, 8.5153e-01, 7.0033e-06, 3.1598e-02, 2.3963e-11,
         2.3612e-06, 1.1645e-01, 2.3049e-04, 1.8342e-04],
        [2.0217e-10, 1.6732e-19, 9.9958e-01, 5.8024e-15, 4.2072e-04, 3.3156e-17,
         6.4231e-11, 6.8843e-07, 3.5534e-09, 1.9625e-09],
        [1.4705e-12, 1.0294e-16, 6.4927e-04, 1.1055e-15, 2.8877e-09, 2.5995e-19,
         9.1552e-10, 9.9935e-01, 1.2993e-09, 7.8726e-11],
        [1.2051e-05, 3.8776e-15, 3.2866e-01, 1.3512e-06, 4.6596e-01, 4.1239e-11,
         4.4367e-09, 2.0472e-01, 6.2775e-06, 6.4708e-04],
        [6.2370e-08, 2.9191

# Part 2-3

network with pytorch

In [0]:
from torch import nn

In [0]:
class Network(nn.Module):
  def __init__(self):
    super().__init__()

    self.hidden = nn.Linear(784,256)
    self.output = nn.Linear(256,10)

    self.sigmoid =nn.Sigmoid()
    self.softmax=nn.Softmax(dim=1)

  def forward(self,x):
    x = self.hidden(x)
    x= self.sigmoid(x)
    x= self.output(x)
    x = self.softmax(x)
    return x

In [0]:
model1 =Network()

In [0]:
model1

Network(
  (hidden): Linear(in_features=784, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
  (sigmoid): Sigmoid()
  (softmax): Softmax(dim=1)
)

In [0]:
class ReluNetwork(nn.Module):
  def __init__(self):
    super().__init__()

    self.hidden1 =nn.Linear(784,128)
    self.hidden2 = nn.Linear(128,64)
    self.output=nn.Linear(64,10)

    self.relu =nn.ReLU()
    self.softmax=nn.Softmax()
  
  def forward(self,x):
    x = self.hidden1(x)
    x = self.relu(x)
    x = self.hidden(2)
    x = self.relu(x)
    x = self.output(x)
    x = self.softmax(x)

    return x

In [0]:
modelrel= ReluNetwork()

In [0]:
modelrel

ReluNetwork(
  (hidden1): Linear(in_features=784, out_features=128, bias=True)
  (hidden2): Linear(in_features=128, out_features=64, bias=True)
  (output): Linear(in_features=64, out_features=10, bias=True)
  (relu): ReLU()
  (softmax): Softmax(dim=None)
)

## Part 3-1

In [0]:
modelseq =nn.Sequential(nn.Linear(784,128),\
              nn.ReLU(),\
              nn.Linear(128,64),\
              nn.ReLU(),\
              nn.Linear(64,10),\
              nn.LogSoftmax(dim=1))

In [0]:
criterion = nn.NLLLoss()

In [0]:
images,lables = next(iter(trainloader))


In [0]:
images = images.view(images.shape[0],-1)

In [0]:
logits = modelseq(images)

In [0]:
loss = criterion(logits,labels)

In [0]:
loss

tensor(2.3129, grad_fn=<NllLossBackward>)