In [0]:

import torch
from torch import nn
import torch.nn.functional as F
from torchvision import datasets, transforms

# Define a transform to normalize the data
transform = transforms.Compose([transforms.ToTensor(),
                                transforms.Normalize((0.5,), (0.5,)),
                              ])
# Download and load the training data
trainset = datasets.MNIST('~/.pytorch/MNIST_data/', download=True, train=True, transform=transform)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=64, shuffle=True)

Extracting /root/.pytorch/MNIST_data/MNIST/raw/train-images-idx3-ubyte.gz to /root/.pytorch/MNIST_data/MNIST/raw


Extracting /root/.pytorch/MNIST_data/MNIST/raw/train-labels-idx1-ubyte.gz to /root/.pytorch/MNIST_data/MNIST/raw


Extracting /root/.pytorch/MNIST_data/MNIST/raw/t10k-images-idx3-ubyte.gz to /root/.pytorch/MNIST_data/MNIST/raw


Extracting /root/.pytorch/MNIST_data/MNIST/raw/t10k-labels-idx1-ubyte.gz to /root/.pytorch/MNIST_data/MNIST/raw
Processing...
Done!






/pytorch/torch/csrc/utils/tensor_numpy.cpp:141: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program.


In [0]:
model =nn.Sequential(nn.Linear(784,128),
                     nn.ReLU(),
                     nn.Linear(128,64),
                     nn.ReLU(),
                     nn.Linear(64,10),
                     nn.LogSoftmax(dim=1))

In [0]:
criterion = nn.NLLLoss()

In [0]:
images,labels = next(iter(trainloader))

In [0]:
images =images.view(images.shape[0],-1)

In [0]:
logits=model(images)

In [0]:
loss = criterion(logits,labels)

In [0]:
print('Before Backwar: \n',model[0].weight.grad)

Before Backwar: 
 None


In [0]:
loss.backward()

In [0]:
print('After :\n',model[0].weight.grad)

After :
 tensor([[-0.0004, -0.0004, -0.0004,  ..., -0.0004, -0.0004, -0.0004],
        [ 0.0001,  0.0001,  0.0001,  ...,  0.0001,  0.0001,  0.0001],
        [ 0.0007,  0.0007,  0.0007,  ...,  0.0007,  0.0007,  0.0007],
        ...,
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [-0.0016, -0.0016, -0.0016,  ..., -0.0016, -0.0016, -0.0016],
        [-0.0014, -0.0014, -0.0014,  ..., -0.0014, -0.0014, -0.0014]])


In [0]:
from torch import optim

In [0]:
optimizer =optim.SGD(model.parameters(),lr=0.01)

In [0]:
images,labels =next(iter(trainloader))
images.resize_(64,784)


tensor([[-1., -1., -1.,  ..., -1., -1., -1.],
        [-1., -1., -1.,  ..., -1., -1., -1.],
        [-1., -1., -1.,  ..., -1., -1., -1.],
        ...,
        [-1., -1., -1.,  ..., -1., -1., -1.],
        [-1., -1., -1.,  ..., -1., -1., -1.],
        [-1., -1., -1.,  ..., -1., -1., -1.]])

In [0]:
optimizer.zero_grad()

In [0]:
output =model(images)

In [0]:
loss =criterion(output,labels)

In [0]:
loss.backward()

In [0]:
print('Gradient',model[0].weight.grad)

Gradient tensor([[-1.1991e-03, -1.1991e-03, -1.1991e-03,  ..., -1.1991e-03,
         -1.1991e-03, -1.1991e-03],
        [-6.7100e-04, -6.7100e-04, -6.7100e-04,  ..., -6.7100e-04,
         -6.7100e-04, -6.7100e-04],
        [ 4.7482e-04,  4.7482e-04,  4.7482e-04,  ...,  4.7482e-04,
          4.7482e-04,  4.7482e-04],
        ...,
        [ 5.2407e-05,  5.2407e-05,  5.2407e-05,  ...,  5.2407e-05,
          5.2407e-05,  5.2407e-05],
        [ 9.1446e-04,  9.1446e-04,  9.1446e-04,  ...,  9.1446e-04,
          9.1446e-04,  9.1446e-04],
        [ 3.0153e-03,  3.0153e-03,  3.0153e-03,  ...,  3.0153e-03,
          3.0153e-03,  3.0153e-03]])


In [0]:
optimizer.step()

In [0]:
print('updated weights - ',model[0].weight)

updated weights -  Parameter containing:
tensor([[-0.0355, -0.0352, -0.0016,  ...,  0.0173, -0.0281,  0.0333],
        [ 0.0003,  0.0236,  0.0156,  ...,  0.0071,  0.0175,  0.0141],
        [ 0.0257, -0.0356, -0.0218,  ...,  0.0279, -0.0208,  0.0052],
        ...,
        [-0.0158,  0.0336, -0.0032,  ..., -0.0042, -0.0012, -0.0244],
        [ 0.0109,  0.0347, -0.0122,  ...,  0.0137, -0.0149, -0.0314],
        [ 0.0284,  0.0220, -0.0145,  ...,  0.0144,  0.0235, -0.0349]],
       requires_grad=True)


In [0]:
optimizer1 = optim.SGD(model.parameters(),lr=0.003)

In [0]:
epochs=15

In [0]:
for e in range(epochs):
  running_loss =0
  for images,labels in trainloader:
    images = images.view(images.shape[0],-1)
    optimizer1.zero_grad()
    output = model(images)
    loss =  criterion(output,labels)
    loss.backward()
    optimizer1.step()
    running_loss+=loss.item()
  else:
    print(f"Training loss : {running_loss/len(trainloader)}")

Training loss : 2.321422120401346
Training loss : 2.3133702351848706
Training loss : 2.308397598612283
Training loss : 2.3054329131457854
Training loss : 2.3036346504174823
Training loss : 2.3025613682610646
Training loss : 2.301931331406778
Training loss : 2.3015689082237194
Training loss : 2.3013629709988006
Training loss : 2.301234339854356
Training loss : 2.3011670427790074
Training loss : 2.301105233143642
Training loss : 2.3010966752383757
Training loss : 2.3010788080788878
Training loss : 2.3010772494619083


In [0]:
import helper

images, labels = next(iter(trainloader))

img = images[0].view(1, 784)
# Turn off gradients to speed up this part
with torch.no_grad():
    logps = model(img)

# Output of the network are log-probabilities, need to take exponential for probabilities
ps = torch.exp(logps)
helper.view_classify(img.view(1, 28, 28), ps)

AttributeError: ignored